sudo: required
language: generic

services:
    - docker
    
before_install:
    - docker build -t vinay252/docker-react -f Dockerfile.dev . 
    
script:
    - docker run vinay252/docker-react npm run test -- --coverage
    
    